version: '3.4'

services:
  multitenantjobtracking.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    networks:
      - net_multitenantjobtracking   
   
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "og~8O+nwAT%5c0a8V8G]G+tEi"
    ports:
      - 1433:1433
    volumes:
      - sqlserver-volume:/var/opt/mssql
    networks:
      - net_multitenantjobtracking   
   
networks:
  net_multitenantjobtracking:
    driver: bridge
    external: true
volumes:
  sqlserver-volume:
