version: '3.4'

services:
  multitenantjobtracking.webapi:
    image: ${DOCKER_REGISTRY-}multitenantjobtrackingwebapi
    build:
      context: .
      dockerfile: src/WebApi/MultiTenantJobTracking.WebApi/Dockerfile


  multitenantjobtracking.client:
    image: ${DOCKER_REGISTRY-}multitenantjobtrackingclient
    build:
      context: .
      dockerfile: src/Client/MultiTenantJobTracking.Client/Dockerfile

networks:
  net_multitenantjobtracking:
    driver: bridge
    external: true
