version: '3.4'

services:
  multitenantjobtracking.webapi:
    image: ${DOCKER_REGISTRY-}multitenantjobtrackingwebapi
    build:
      context: .
      dockerfile: src/WebApi/MultiTenantJobTracking.WebApi/Dockerfile


networks:
  net_multitenantjobtracking:
    driver: bridge
    external: true